name: Deploy to GitHub Pages

on:
  push:
    branches:
      - v2

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout v2
        uses: actions/checkout@v4

      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .
          clean: true
          clean-exclude: |
            .nojekyll
